[gaim-migrate @ 17723] This fixes by console Gaim compile errors:
gntwm.c: In function 'reverse_char':
gntwm.c:574: error: implicit declaration of function 'mvwin_wch'
gntwm.c:578: error: implicit declaration of function 'mvwadd_wch'


What was happening was, gntwm.h #includes <panel.h> before
<ncurses.h> gets #included.  And on my system
/usr/ncursesw/panel.h #includes <ncurses/curses.h>, which
doesn't have mvwin_wch or wvmadd_wch.

So basically ncurses.h needs to be the first ncurses include.
Otherwise we might get the wrong ncurses.h